name: ILM - Notification - Inactive User Accounts

on:
  workflow_dispatch:
    inputs:
      Entity:
        description: "Please provide Entity - ACS_AGSO | AEIS | AGMS | AIGI | ARC_ARF | ARE_ARL | AMIS"
        required: true

jobs:
    Print_in_screen_ACS_AGSO:
      name: Print - ACS_AGSO
      #if: contains(github.event.schedule, '30 21 5 * 1')
      if: ${{ github.event.inputs.Entity == 'ACS_AGSO' }}
      runs-on: windows-latest
      timeout-minutes: 180

      steps:
        - uses: actions/checkout@v2
        - name: Run write-host
          shell: pwsh
          run: |
              write-host "this is for ACS_AGSO"
              write-host "$($pwd)"
              $currentDir = $pwd
              cd AMIS/product/prod1/common/scripts
              
              $CSVPath = $currentDir + "AMIS/product/prod2/prod2.csv"
              
              ./prod1.ps1 -workingDirectory $CSVPath
  
    Print_in_screen_AEIS:
      name: Print - AEIS
      if: ${{ github.event.inputs.Entity == 'AEIS' }}
      runs-on: windows-latest
      timeout-minutes: 180
    
      steps:
        - uses: actions/checkout@v2          
        - name: Run write-host
          shell: pwsh
          run: |
            write-host "this is for AEIS"        
        
