name: ILM - Notification - Inactive User Accounts

on:
  workflow_dispatch:
    inputs:
      Entity:
        description: "Please provide Entity - ACS_AGSO | AEIS | AGMS | AIGI | ARC_ARF | ARE_ARL | AMIS"
        required: true

jobs:
    Print_in_screen_ACS_AGSO:
      name: Print - ACS_AGSO
      #if: contains(github.event.schedule, '30 21 5 * 1')
      #if: contains(github.event.inputs.Entity, 'ACS_AGSO')
      runs-on: windows-latest
      timeout-minutes: 180

      steps:
        - uses: actions/checkout@v2
          with:
            ref: master

        - name: Run write-host
          if: ${{ github.event.inputs.Entity == 'ACS_AGSO' }}
          run: |
              write-host "this is for ACS_AGSO"
  
    Print_in_screen_AEIS:
      name: Print - AEIS
      runs-on: windows-latest
    
      steps:
        - uses: actions/checkout@v2
          with:
            ref: master
            
        - name: Run write-host
          if: ${{ github.event.inputs.Entity == 'AEIS' }}
          run: |
            write-host "this is for AEIS"        
        
