#nmn-test

name: nmn.yml

#on: [push]
on: workflow_dispatch

jobs:
  initialize_vars:
    name: Initialize Variables for use in subsequent Jobs
    runs-on: windows-latest
    
    steps:
      - name: Initialize
        id: initialize
        run: |
          $AppID = "Application1234"
          $TenantID = "Tenant1234"

          echo "AppID=$($AppID)" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "TenantID=$($TenantID)" | Out-File -FilePath $env:GITHUB_ENV -Append

  print_vars:
    name: Print Variables
    needs: [initialize_vars]
    runs-on: windows-latest

    steps:
      - name: Print
        run: |
          $application = {{ steps.initialize.outputs.AppID }}
          $tenant = {{ env.TenantID }}

          Write-Host "AppID: $($application)"
          Write-Host "TenantID: $($tenant)"

          echo "${{ env.AppID }}"
          echo "${{ env.TenantID }}"
