#nmn-test

name: nmn.yml

on: [push]

jobs:
  
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: print_word
      run: |
       echo "pushed file" >> nnabong\nmn_git\README.md
       echo "done"