#nmn-test

name: nmn.yml

#on: [push]
on: workflow_dispatch

jobs:
  initialize_vars:
    name: Initialize Variables for use in subsequent Jobs
    runs-on: windows-latest
    
    steps:
      - name: Initialize
        id: initialize
        run: |
          $AppID = "Application1234"
          $TenantID = "Tenant1234"

          Write-Output "AppID=$($AppID)" >> $Env:GITHUB_OUTPUT
          Write-Output "TenantID=$($TenantID)" >> $Env:GITHUB_OUTPUT

  print_vars:
    name: Print Variables
    needs: [initialize_vars]
    runs-on: windows-latest

    steps:
      - name: Print
        run: |
          Write-Host "AppID: {{ steps.initialize.outputs.AppID }}"
          Write-Host "TenantID: {{ steps.initialize.outputs.TenantID }}"
