#nmn-test

name: nmn.yml

#on: [push]
on: workflow_dispatch

jobs:
  test_vars:
    name: Test Variables for use in subsequent Jobs
    runs-on: windows-latest
    
    steps:
      - name: Initialize
        id: initialize
        run: |
          $AppID = "Application1234"
          $TenantID = "Tenant1234"

          echo "AppID=$($AppID)" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "TenantID=$($TenantID)" | Out-File -FilePath $env:GITHUB_ENV -Append
          
      - name: Print
        run: |

          $app = "${{ env.AppID }}"
          $tenant = "${{ env.TenantID }}"

          echo "$($app) and $($tenant)"
