#nmn-test

name: nmn.yml

#on: [push]
on: workflow_dispatch

jobs:
  initialize_vars:
    name: Initialize Variables for use in subsequent Jobs
    runs-on: windows-latest
    
    steps:
      - name: Initialize
        id: initialize
        run: |
          $AppID = "Application1234"
          $TenantID = "Tenant1234"

          echo ::set-output name=AppID::$( $AppID)
          echo ::set-output name=TenantID::$( $TenantID)
          Write-Output "AppID=$($AppID)" >> $Env:GITHUB_OUTPUT
          Write-Output "TenantID=$($TenantID)" >> $Env:GITHUB_OUTPUT

  print_vars:
    name: Print Variables
    runs-on: windows-latest

    steps:
      - name: Print
        run: |
          Write-Host "{{ steps.initialize.outputs.AppID }}"
          Write-Host "{{ steps.initialize.outputs.TenantID }}"
