name: Sync DL Members AMIS - All

on: workflow_dispatch

jobs:
    Sync_DL_Members:
      name: Sync DL Members AMIS - All
      runs-on: windows-latest

      steps:
        - name: Run Sync-DLMembers.ps1
          run: |
            $SourceGroup = "AMIS - All Staff"
            $TargetGroup = "amis-all@archcapservices.com"

            echo $SourceGroup
            echo $TargetGroup
