name: Test Run - Repository Dispatch

on:
  repository_dispatch:
    types:
      [
        test_run_repo_dispatch,
      ]

env:
  app_name:  ${{ github.event.client_payload.app_name }}
  app_owner: ${{ join(github.event.client_payload.app_owner, ',') }}
  payload: ${{ toJSON(github.event.client_payload) }}
  ticket_number: ${{ github.event.client_payload.servicenow_details.ticket_number }}
  snow_instance: ${{ github.event.client_payload.servicenow_details.snow_instance }}
  ANSIBLE_FORCE_COLOR: '1'


jobs:
    ## JOB: Create Azure App Registration
    azure_ad_app_registration:
      name: Create Azure App Registration
      runs-on: ubuntu-latest
      timeout-minutes: 20

      defaults:
        run:
          working-directory: "/home/runner/work/nmn_git/nmn_git"

      steps:
        - name: Echo out the input variables
          run: |
            echo 'client_payload: ${{ env.payload }}'
            echo 'App Name = ${{ env.app_name }}'
            echo 'App Name again = ${{ github.event.client_payload.app_name }}'
            echo 'App Owner = ${{ join(github.event.client_payload.app_owner, ',') }}'

            $app_owners = '${{ env.app_owner }}'

            echo $app_owners.gettype()
            



